services: # Aplicaciones a ejecutar:
  db: # LLamada a base de datos
    image: timescale/timescaledb:latest-pg16 # La versión de la base de datos
    container_name: fitgame_db
    restart: always # Si el pc se reinicia o el contenedor falla, el docker lo volverá a levantar automáticamente
    environment: # Variables de entorno
      POSTGRES_USER: admin_821011 # Nombre de admin de la base de datos
      POSTGRES_PASSWORD: "0000" # Contraseña admin
      POSTGRES_DB: fitgame # Nombre de la base de datos
    ports: # tunel
      - "5432:5432" # Conecta el puerto del contenedor con el de tu PC
    volumes:
      - postgres_data:/var/lib/postgresql/data # Para que los datos no se borren al apagar

volumes: # La memoria
  postgres_data: # Zona de memoria persistente en disco donde se guardan los datos llamado postgres_data